name: campus_ride_sharing_step1
description: Campus Ride Sharing - Step 1 Baseline (Firebase Auth + Roles)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_places_flutter: ^2.0.6
  image_picker: ^1.0.7
  firebase_core: ^3.6.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.0.2
  fluttertoast: ^8.2.6
  uuid: ^4.4.2
  google_sign_in: ^6.1.0
  provider: ^6.0.5
  intl: ^0.18.1 
  google_maps_flutter: ^2.6.1
  location: ^6.0.2
  razorpay_flutter: ^1.3.4
  geolocator: ^10.1.0
  firebase_storage: ^12.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
